# Generated by Django 5.0.3 on 2024-04-21 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Avtomobillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Avtomobil nomi')),
                ('content', models.TextField(verbose_name="Avtomobil haqida to'liq ma'lumot")),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Rasmi')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('published', models.BooleanField(default=True, verbose_name='Saytga chiqarish')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elonlar.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
                'ordering': ['-created', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=25, verbose_name='\\Email manzil')),
                ('phone', models.CharField(max_length=13, verbose_name='Telefon raqam')),
                ('photo', models.ImageField(blank=True, upload_to='profile_pictures/', verbose_name='Rasmi')),
                ('mobile', models.CharField(max_length=13, verbose_name='Telefon raqam1')),
                ('addres', models.CharField(max_length=50, verbose_name='Manzil')),
                ('full_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="To'liq ism")),
            ],
        ),
    ]
